"""adjust GameModel, for new params

Revision ID: d40f88a51bd3
Revises: ea968bcbf00d
Create Date: 2021-04-15 11:18:07.612880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd40f88a51bd3'
down_revision = 'ea968bcbf00d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('Mega_sena_result', sa.String(), nullable=True))
    op.add_column('games', sa.Column('Result_sort', sa.String(), nullable=True))
    op.add_column('games', sa.Column('correct_numbers', sa.String(), nullable=True))
    op.alter_column('games', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('games', 'correct_numbers')
    op.drop_column('games', 'Result_sort')
    op.drop_column('games', 'Mega_sena_result')
    # ### end Alembic commands ###
